require("ivankunstlerdev.plugins.vague")
require("ivankunstlerdev.plugins.fzf")
require("ivankunstlerdev.plugins.lazydev")
require("ivankunstlerdev.plugins.blink")
require("ivankunstlerdev.plugins.mini-pairs")
require("ivankunstlerdev.plugins.lspconfig")
require("ivankunstlerdev.plugins.treesitter")
require("ivankunstlerdev.plugins.nvim-tree")
